// Barrel — single import surface for @cc-viewer/shared consumers.
export * from './types.js';
export * from './weights.js';
export * from './report.js';
export * from './projections/tool-interactions.js';
export * from './projections/token-series.js';
export * from './projections/file-touch.js';
export * from './projections/usage-dedup.js';
export * from './projections/api-error-chains.js';
export * from './projections/sticky-state.js';
export * from './projections/session-summary.js';

// JSONL schema — the new authoritative wire types (007-ui-information-revamp).
// `UsageBlock` is intentionally omitted; the legacy interface in ./types.ts is
// the canonical name. The schema's inferred shape is exposed as `UsageBlockSchema`'s
// `z.infer` for callers that need it.
export {
  // Schemas (Zod validators)
  EnvelopeSchema,
  UsageBlockSchema,
  TextBlockSchema,
  ThinkingBlockSchema,
  ToolUseBlockSchema,
  AssistantContentBlockSchema,
  ImageBlockSchema,
  ToolReferenceBlockSchema,
  ToolResultBlockSchema,
  UserContentBlockSchema,
  ToolResultContentSchema,
  StructuredPatchHunkSchema,
  BashResultSchema,
  ReadFileResultSchema,
  EditResultSchema,
  WriteResultSchema,
  MultiFileResultSchema,
  TaskCreateResultSchema,
  TaskUpdateResultSchema,
  TaskListResultSchema,
  AgentRollupResultSchema,
  AgentLaunchResultSchema,
  ToolSearchResultSchema,
  AskUserQuestionResultSchema,
  ExitPlanResultSchema,
  WebSearchResultSchema,
  WebFetchResultSchema,
  SlashCommandAgentResultSchema,
  CommandPermissionResultSchema,
  ExitWorktreeResultSchema,
  ToolUseResultSchema,
  AttachmentPayloadSchema,
  UserRowSchema,
  AssistantRowSchema,
  SystemSubtypeEnum,
  SystemRowSchema,
  AttachmentRowSchema,
  AiTitleRowSchema,
  CustomTitleRowSchema,
  AgentNameRowSchema,
  PermissionModeEnum,
  PermissionModeRowSchema,
  LastPromptRowSchema,
  PrLinkRowSchema,
  WorktreeStateRowSchema,
  QueueOperationRowSchema,
  FileHistorySnapshotRowSchema,
  ClaudeRowSchema,
  UnknownRowSchema,
  ClaudeRowOrUnknownSchema,
  SubagentMetaSchema,
  // Attachment payload schemas
  DirectoryAttachmentSchema,
  FileAttachmentSchema,
  EditedTextFileAttachmentSchema,
  NestedMemoryAttachmentSchema,
  SkillListingAttachmentSchema,
  DeferredToolsDeltaAttachmentSchema,
  McpInstructionsDeltaAttachmentSchema,
  TaskReminderAttachmentSchema,
  AutoModeAttachmentSchema,
  AutoModeExitAttachmentSchema,
  PlanModeAttachmentSchema,
  PlanModeExitAttachmentSchema,
  PlanModeReentryAttachmentSchema,
  UltrathinkEffortAttachmentSchema,
  QueuedCommandAttachmentSchema,
  DateChangeAttachmentSchema,
  CommandPermissionsAttachmentSchema,
  GoalStatusAttachmentSchema,
  HookSuccessAttachmentSchema,
  HookBlockingErrorAttachmentSchema,
  HookNonBlockingErrorAttachmentSchema,
  HookCancelledAttachmentSchema,
  // Predicates
  isUserRow,
  isAssistantRow,
  isSystemRow,
  isAttachmentRow,
  isToolResultRow,
  isHumanPromptRow,
} from './jsonl/schema.js';

export type {
  Envelope,
  TextBlock,
  ThinkingBlock,
  ToolUseBlock,
  AssistantContentBlock,
  ImageBlock,
  ToolReferenceBlock,
  ToolResultBlock,
  UserContentBlock,
  StructuredPatchHunk,
  BashResult,
  ReadFileResult,
  EditResult,
  WriteResult,
  MultiFileResult,
  TaskCreateResult,
  TaskUpdateResult,
  TaskListResult,
  AgentRollupResult,
  AgentLaunchResult,
  ToolSearchResult,
  AskUserQuestionResult,
  ExitPlanResult,
  WebSearchResult,
  WebFetchResult,
  ToolUseResult,
  AttachmentPayload,
  UserRow,
  AssistantRow,
  SystemRow,
  AttachmentRow,
  AiTitleRow,
  CustomTitleRow,
  AgentNameRow,
  PermissionModeRow,
  LastPromptRow,
  PrLinkRow,
  WorktreeStateRow,
  QueueOperationRow,
  FileHistorySnapshotRow,
  ClaudeRow,
  UnknownRow,
  ClaudeRowOrUnknown,
  SubagentMeta,
} from './jsonl/schema.js';
